name: camagru

services:
  model:
    container_name: model
    env_file: .env
    build:
      context: ./model
      dockerfile_inline: 
        FROM  mysql:latest

        CMD ["mysqld", "--console"]
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - camagru_net

  # view:
  #   container_name: view
  #   env_file: .env
  #   build:
  #     context: ./view
  #     dockerfile_inline:
  #       FROM  nginx:alpine

  #       COPY index.html .
  #   restart: always
  #   networks:
  #     - camagru_net
  #   volumes:
  #     - type: bind
  #       source: ./static
  #       target: /static


  controller:
    container_name: controller
    env_file: .env
    build:
      context: ./controller
      dockerfile_inline:
        FROM    node:24-alpine

        ARG		SERV_PORT=${SERV_PORT} 
        EXPOSE	${SERV_PORT}
        ARG		SERV_ADDRESS=${SERV_ADDRESS}
        ARG		SERVF=${SERVF}

        RUN   apk update && apk upgrade && apk fetch vim

        CMD 	["node", "${SERVF}"]
    restart: always
    volumes:
      - type: bind
        source: ./controller
        target: /controller
      # - controller:/home/davidjwp/camagru
      - type: bind
        source: ./view
        target: /view
    ports:
      - "${SERV_PORT}:${SERV_PORT}"
    networks:
      - camagru_net


volumes:
  mysql:
    name: mysql
  # view:
  #   name: view
# this is temporary for work, in the final version controller copies the local file 
# into the container
  controller:
    name: controller

networks:
  camagru_net:
    driver: bridge
