name: camagru

services:
  model:
    container_name: model
    env_file: .env
    build:
      context: ./model
      dockerfile_inline: 
        FROM  mysql:latest

        CMD ["mysqld", "--console"]
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - camagru_net

  view:
    container_name: view
    env_file: .env
    build: 
      context: ./view
      dockerfile_inline:
        FROM  node:22-alpine

        RUN   apk update && apk upgrade && apk fetch vim

        RUN npm install


    restart: always
    volumes:
      - view:/home/davidjwp/view
    networks:
      - camagru_net

  controller:
    container_name: controller
    env_file: .env
    build:
      context: ./controller
      dockerfile_inline:
        FROM    node:24-alpine

        ADD     ${SERVF} .

        RUN   apk update && apk upgrade && apk fetch vim

        CMD 	["node", "${SERVF}"]
    restart: always
    volumes:
      - controller:/home/davidjwp/camagru
    ports:
      - "${SERV_PORT}:${SERV_PORT}"
    networks:
      - camagru_net


volumes:
  mysql:
    name: mysql
  view:
    name: view
# this is temporary for work, in the final version controller copies the local file 
# into the container
  controller:
    name: controller

networks:
  camagru_net:
    driver: bridge
