name: camagru

services:
  # model:
  #   container_name: model
  #   env_file: .env
  #   build:
  #     context: ./model
  #     dockerfile_inline: 
  #       FROM  mysql:latest

  #       CMD ["mysqld", "--console"]
  #   volumes:
  #     - mysql:/var/lib/mysql
  #   networks:
  #     - camagru_net

  controller:
    container_name: controller
    env_file: .env
    build:
      args: 
        SERV_PORT: ${SERV_PORT}
        SERV_ADDRESS: ${SERV_ADDRESS}
      context: ./controller      
    restart: always
    develop:
      watch:
        - action: sync
          path: ../view
          target: /var/www/html
        - action: sync
          path: ./controller/etc
          target: /etc
    volumes:
      - type: bind
        source: ./controller/etc
        target: /var/www/html
    ports:
      - "${SERV_PORT}:${SERV_PORT}"
    networks:
      - camagru_net


volumes:
  mysql:
    name: mysql
  # view:
  #   name: view
# this is temporary for work, in the final version controller copies the local file 
# into the container
  controller:
    name: controller

networks:
  camagru_net:
    driver: bridge