name: camagru

services:
  # model:
  #   container_name: model
  #   image: mysql:latest
    
  #   env_file: .env
  #   # build:
  #   #   context: ./model
  #   #   dockerfile_inline: 
  #   #     FROM  mysql:latest

  #   #     CMD ["mysql", ]
  #   volumes:
  #     - mysql:/var/lib/mysql
  #   networks:
  #     - camagru_net

  # view:
  #   container_name: view
  #   env_file: .env
  #   build: 
  #     context: ./view
  #     dockerfile_inline:
  #       FROM  debian:latest

  #       CMD ["echo", "hello"]

  #   restart: always
  #   networks:
  #     - camagru_net

  controller:
    container_name: controller
    env_file: .env
    build:
      context: ./controller
      dockerfile_inline: |
        FROM    node:24-alpine

        EXPOSE	${SERV_PORT}
        ADD     ${SERVF} .

        RUN   apk update && apk upgrade && apk fetch vim

        CMD 	["node", "${SERVF}"]
    restart: always
    ports:
      - 8000
    networks:
      - camagru_net


# volumes:
#   mysql:
#     name: mysql

networks:
  camagru_net:
    driver: bridge
